context("qtlRaster")
library(assignR)
data("naMap")
data("d2h_lrNA")
d = subOrigData(taxon = "Homo sapiens", dataset = 10, mask = naMap)
r = calRaster(known = d, isoscape = d2h_lrNA, mask = naMap)
id = c("A", "B", "C", "D")
d2H = c(-110, -90, -105, -102)
un = data.frame(id, d2H)
asn = pdRaster(r,unknown=un,mask=naMap)
q1 = qtlRaster(asn, threshold = 0.1, thresholdType = "area")
q2 = qtlRaster(asn, threshold = 0.1, thresholdType = "prob")
q3 = qtlRaster(asn, threshold = 0)

test_that("qtlRaster works",{
            expect_is(q1, "RasterStack")
            expect_equal(nlayers(q1), 4)
            expect_equal(nlayers(q2), 4)
            expect_equal(nlayers(q3), 4)
            expect_error(qtlRaster(asn, threshold = "a"))
            expect_error(qtlRaster(asn, threshold = 10))
            expect_error(qtlRaster(asn, threshold = "a"), thresholdType = "probability")
            expect_error(qtlRaster(asn, threshold = 0.1, genplot = "A"))
            expect_error(qtlRaster(asn, threshold = 0.1, outDir = 1))
            
})
