# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: ubuntu-18.04,   r: 'release'}
          - {os: windows-latest,   r: 'devel'}
          - {os: windows-latest,   r: '3.6'}
          
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up R ${{ matrix.config.r }}
        uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}
      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@master
        with:
          pandoc-version: '2.7.3'
      - run: echo "# Test" | pandoc -t html
      - name: Windows setup
        if: runner.os == 'windows-latest'
        run: |
          nuget: CurlThin.Native, 0.0.8
      - name: Linux setup
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install gdal-bin proj-bin libgdal-dev libproj-dev
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
