name: R

on:

  push:
    branches: [ master ]
    
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'release'}
          - {os: windows-latest, arch: x64, r: 'devel'}
          - {os: windows-latest, r: '4.0.0'}
          
    steps:
      - name: Run checkout
        uses: actions/checkout@v4
      
      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@v2
          
      - name: Set up R ${{ matrix.config.r }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true
          
      - name: Mac setup
        if: runner.os == 'macOS'
        run: brew install gdal
          
      - name: Linux setup
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install gdal-bin proj-bin libgdal-dev libproj-dev
          
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck

      - name: Check package
        uses: r-lib/actions/check-r-package@v2
        with:
          error-on: '"error"'
