on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: test-coverage

jobs:
  test-coverage:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2

      - name: Install gdal
        run: |
          find /usr/local/bin -type l -ilname '*/Library/Frameworks/Python.framework/*' -delete
          brew install gdal
          
      - uses: r-lib/actions/setup-r-dependencies@v2
          
      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
